### ISSUE TITLE
Binary for linux-x64 is not working as expected.

### ISSUE THREAD

**Issue by karliatto** [trezor/coinjoin-backend#11]
When running the binary `linux-x64` from https://github.com/trezor/coinjoin-backend/pkgs/container/coinjoin-backend  and then sending a POST request to `http://127.0.0.1:37128/Cryptography/analyze-transaction` I get 500 http error and the logs from the binary throw error like below. It looks like is looking for file called `WalletWasabi.WabiSabiClientLibrary.xml` and it is not there.

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMLAPAE515K9", Request id "0HMLAPAE515K9:00000002": An unhandled exception was thrown by the application.
      System.IO.FileNotFoundException: Could not find file '/home/user/linux-x64/WalletWasabi.WabiSabiClientLibrary.xml'.
```

For clarification I used the simple nodejs script bellow for sending the http POST request:

```javascript
const fetch = require('cross-fetch');

fetch('http://127.0.0.1:37128/Cryptography/analyze-transaction', {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json-patch+json',
    },
    body: JSON.stringify({ transactions: [] }),
}).then(resp => {
    console.log('resp', resp);
});
```

Any idea why this could be happening? is it working for someone else?

**Comment by karliatto** [comment]
I made it work with including `WalletWasabi.WabiSabiClientLibrary.xml` in the directory where the binary is. Should we include that file along the binary or is something that should be fixed in the binary ?

**Comment by szymonlesisz** [comment]
to be precise, looks all builds are not working properly (without this xml file)

**Comment by prusnak** [comment]
So let's just bundle the xml file too?

**Comment by onvej-sl** [comment]
It seems to me the xml file is only used by swagger, so I removed swagger from the binary. Can you please retest if it works? https://github.com/trezor/coinjoin-backend/actions/runs/3234644449#artifacts

**Comment by onvej-sl** [comment]
> It seems to me the xml file is only used by swagger, so I removed swagger from the binary. Can you please retest if it works? https://github.com/trezor/coinjoin-backend/actions/runs/3234644449#artifacts

It doesn't seem to work. Give me one more try.

**Comment by onvej-sl** [comment]
It should be OK now. https://github.com/trezor/coinjoin-backend/actions/runs/3235111698#artifacts

**Comment by karliatto** [comment]
@onvej-sl thanks! It seams to work now without the `.xml` file

**Comment by bosomt** [comment]
**QA OK**

https://www.notion.so/satoshilabs/CJ-middleware-binaries-ac11048cf3b142c7a606e4b65170bfa6
