### ISSUE TITLE
Are the binaries for middleware going to be in a release?

### ISSUE THREAD

**Issue by karliatto** [trezor/coinjoin-backend#12]
Currently the provided binaries for coinjoin middleware ( https://github.com/trezor/coinjoin-backend/actions/runs/3235111698#artifacts) are the artifacts of a GitHub actions job, that makes it downloadable manually when I am logged in to GitHub but does not allow to download them from a script without logging in.

Are there plans to include those binaries as releases anytime?

I guess there is no rush for that downloading then manually now is fine, but just curious about the plans.

**Comment by vdovhanych** [comment]
Yes, we plan on having the binaries as a release once it is in a more complete state.

**Comment by szymonlesisz** [comment]
resolved by https://github.com/trezor/WalletWasabi/commit/6a4a1b9c69a075bb635fa96ee218984294bc0b33
implemented in suite https://github.com/trezor/trezor-suite/pull/7658
