### ISSUE TITLE
Create a signed binary for osx-arm64

### ISSUE THREAD

**Issue by karliatto** [trezor/coinjoin-backend#14]
Binary for M1 mac from job https://github.com/trezor/coinjoin-backend/actions/runs/3267204483#artifacts does not work.

**Comment by prusnak** [comment]
The binary is not notarised, so it is being killed by the OS.

Hopefully, when the binary is packaged into the Electron installer, they are signed/notarised. But this does not help much with the development, though.

**Comment by vdovhanych** [comment]
Im not sure its related to macOS security restrictions.
```
 ~/Downloads/CoinjoinClientLibrary-binary/osx-arm64/publish                                                                                                                                                                                                                                                                                                                        ✘ KILL
❯ ls
 WalletWasabi.WabiSabiClientLibrary

 ~/Downloads/CoinjoinClientLibrary-binary/osx-arm64/publish                                                                                                                                                                                                                                                                                                                              
❯ xattr -d com.apple.quarantine WalletWasabi.WabiSabiClientLibrary 

 ~/Downloads/CoinjoinClientLibrary-binary/osx-arm64/publish                                                                                                                                                                                                                                                                                                                              
❯ ./WalletWasabi.WabiSabiClientLibrary 
zsh: killed     ./WalletWasabi.WabiSabiClientLibrary

 ~/Downloads/CoinjoinClientLibrary-binary/osx-arm64/publish                                                                                                                                                                                                                                                                                                                        ✘ KILL
❯ xattr WalletWasabi.WabiSabiClientLibrary 
com.apple.lastuseddate#PS
com.apple.macl
```
if you remove the quarantine(should allow any app to start) it still crashes. **Also Intel version of the binary works on m1 macs using rosseta.**

**Comment by prusnak** [comment]
The binary works for me after applying `xattr -d com.apple.quarantine WalletWasabi.WabiSabiClientLibrary`

**Comment by prusnak** [comment]
The following fixes the issue for me:

``` bash
# set executable flag
chmod +x WalletWasabi.WabiSabiClientLibrary

# code sign the binary using "ad-hoc signing"
codesign -s - WalletWasabi.WabiSabiClientLibrary

# remove quarantine flag
xattr -d com.apple.quarantine WalletWasabi.WabiSabiClientLibrary 
```

**Comment by vdovhanych** [comment]
Well, I needed to run codesign on the binary then it launches, why does the intel binary launch without it, strange..

**Comment by matejkriz** [comment]
yes, `codesign -s - packages/suite-data/files/bin/coinjoin/osx-arm64/WalletWasabi.WabiSabiClientLibrary` fixes it for me too 🎉  we could live with that temporary, but we need to find better solution (sign it during build of the /WalletWasabi.WabiSabiClientLibrary binary?)

**Comment by karliatto** [comment]
I changed the name of this issue to be an actionable issue.
@vdovhanych do you think once there is a release of these binaries would be possible to sign them (at least the one for oxs-arm64)?

**Comment by vdovhanych** [comment]
Yes that should be possible

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (5d1bc34fcbf5ed351a680893b6586cb8bbca8c08)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision fac4e2f157ca7d0c782b8a55175478e476ea7e28)
 - Transport: bridge 2.0.32

**Comment by karliatto** [comment]
Closing this one and opening a follow-up https://github.com/trezor/coinjoin-backend/issues/15
